name: medicnest_pro
description: "MedicNest Medical Professional app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  onboarding: ^4.0.2
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.0.13
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  intl: ^0.19.0
  provider: ^6.0.4
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  pinput: ^4.0.0
  agora_rtc_engine: ^6.0.0
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: 'Lato'
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700